name: fasum_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_app_check:
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  geolocator: ^14.0.0
  google_generative_ai: ^0.4.7
  shimmer: ^3.0.0
  androidx.core.:core: ^1.16.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
